### PR TITLE
added Data Generation tool in implementations list

### PR DESCRIPTION
**Pull request by ducin**
[JSON Schema Faker](https://github.com/json-schema-faker/json-schema-faker) is a popular tool used to generate massive amounts of fake data that conform to JSON Schema specification.

### CODE REVIEW

**Comment by geraintluff** [comment]
Hmm, yeah - there are enough of these now that we probably do need a section for it.

We should move Schematic Ipsum, JSON-Schema-Instantiator and JSON Schema Random to this section (currently filed in ["Other"](https://github.com/json-schema-faker/json-schema/blob/36d8d75c270eb840c19b72869adef47b7a8c9e2c/implementations.html#L261-L263)).

**Comment by ducin** [comment]
@geraintluff Shall I do something more here?

**Comment by geraintluff** [comment]
If you could split out the "Other" section into "Data generation" and "Other", adding yours to the existing two in "Data generation", that would be amazing.

**Comment by ducin** [comment]
@geraintluff I've done that.

**Comment by geraintluff** [comment]
Nice - thanks.

**Pull request merged**
