### PR TITLE
Site: minor updates to markup and CSS

### PR DESCRIPTION
**Pull request by Zearin**
These are slight tweaks to the markup (to improve semantics) and CSS (to maintain styles, or add minor enhancements) for the website.

### CODE REVIEW

**Comment by geraintluff** [comment]
These changes make sense to me.  (Automatic merge failed, presumably due to another PR just accepted.)

Tagging in @Relequestual - he's looking at the possibility of overhauling the site.  The work's happening over at [json-schema-org.github.io](https://github.com/json-schema-org/json-schema-org.github.io), so if you wanted to discuss things with him that would be the place.

**Comment by Relequestual** [comment]
Thanks @geraintluff - I have to apologies for not having been able to properly submit my proposal (as I said I would!) It's been a bit busy at work and home for the past few weeks. Hoping I can submit my proposal before the end of next week, and then commence work a week or so after.

**Comment by geraintluff** [comment]
There are conflicts for some reason - I'd be happy to merge this in, though.

**Comment by Relequestual** [comment]
@Zearin If you can resolve the conflicts, then feel free to go ahead =]

**Comment by Zearin** [comment]
Sorry it took me a while to get back to this!  There should be no conflicts now.

**Comment by Relequestual** [comment]
I'd be happy to review this and give it +1 if it all looks good, unless @geraintluff can find the time. Of course, you'll have to then accept the pull request. Feel free to assign this PR to myself.

(apologies, I have been on leave for the last week)

**Pull request closed without merging**
