### PR TITLE
Add Elixir validator ex_json_schema to the list of implementations

### PR DESCRIPTION
**Pull request by jonasschmidt**
I recently created a draft 4-compliant validator written in Elixir that passes the official test suite. Please add it to the list of implementations.

### CODE REVIEW

**Comment by duksis** [comment]
:+1:

**Comment by duksis** [comment]
@Julian
Just for the sake of curiosity could you give some reasoning behind why this is not being accepted?

Thanks for your time - really appreciated 🙇

**Comment by Julian** [comment]
Sorry, this and a bunch of other PRs were closed somewhat unintentionally, we're moving hosting to json-schema-org/json-schema-org.github.io

**Comment by duksis** [comment]
:)

**Pull request closed without merging**
