### PR TITLE
Add link to open source benchmark for JavaScript implementations

### PR DESCRIPTION
**Pull request by ebdrup**

### CODE REVIEW

**Comment by gilesbowkett** [comment]
-1

I'd prefer to see a **_section_** about benchmarking. You wrote your benchmarks [after](https://github.com/pandastrike/jsck/pull/73) [several](https://github.com/pandastrike/jsck/issues/72) [conversations](https://github.com/pandastrike/jsck/pull/78) about the JSCK benchmarks, and [the JSCK benchmarks were based on the Cosmic Realms benchmarks](http://gilesbowkett.blogspot.com/2015/01/why-panda-strike-wrote-fastest-json.html#jsck-benchmarks).

Lots of other JSON Schema validators have their own built-in benchmarking (for instance [themis](https://github.com/playlyfe/themis/tree/master/benchmark) and z-schema) and there's even a tiny amount of [primitive benchmarking in the enjoi project](https://github.com/tlivings/enjoi#performance), for converting JSON Schema into joi's schema format.

It'd be better to have something which reveals how much benchmarking is going on, and maybe which even inspires people to consolidate their efforts a little.

**Comment by Muscula** [comment]
Actually the benchmarks at https://github.com/Muscula/json-schema-benchmark are derived from the themis benchmarks, that are derived from the z-schema benchmarks. The JSCK Benchmarks are not stable as discussed [here](https://github.com/pandastrike/jsck/issues/81)

Having benchmarks done by someone not involved in writing validators is the best option IMHO. Let it be a joined effort to a common benchmark. One schema validator author [already contributed](https://github.com/Muscula/json-schema-benchmark/pull/7) to making the benchmarks at https://github.com/Muscula/json-schema-benchmark better. Adding the things needed to make remote ref tests pass for **all** validators that support this.

**Comment by gilesbowkett** [comment]
> The JSCK Benchmarks are not stable as discussed here

Well, that discussion is actually a discussion about how those benchmarks are not statistically robust. Typically "stable" has a different meaning in a discussion of software. But sure, they're not perfect.

> The need of a third-party test is also demonstrated by you updating you readme. But failing to update the benchmarks section of you readme. Where the benchmarks you display does not include themis or is-my-json-valid that are faster than jsck in you own benchmarks

Dude, that really just demonstrates that this is a weekend. I'm 100% confident that is-my-json-valid is faster than JSCK, but not 100% confident re Themis, because I haven't run the official JSON Schema tests against it yet, and I've got other stuff to do right now. So I updated the `README` to be generally accurate and I'll make it more specific when I've got the time.

`¯\_(ツ)_/¯`

**Comment by Muscula** [comment]
> Dude, that really just demonstrates that this is a weekend. I'm 100% confident that is-my-json-valid is  faster than JSCK, but not 100% confident re Themis, because I haven't run the official JSON Schema tests against it yet, and I've got other stuff to do right now. So I updated the README to be generally accurate and I'll make it more specific when I've got the time.

This was my point, I'm not saying you are trying to hide things, I'm just saying that your focus is building a awesome validator, not building a awesome benchmark + test of compliance for all validators.

**Comment by gilesbowkett** [comment]
Well, a) I'm not trying to say don't build your benchmarks, just saying give credit to all the other ones which already exist.

And b) building awesome automated benchmarks and compliance tests **_is_** something we've spent weeks and weeks of time on. Our benchmarks test against more schemas than yours, our compliance tests work great, and are very succinct, and again,

c) all I'm actually asking you to do is acknowledge that they exist.

**Comment by Muscula** [comment]
I'd be more than happy to acknowledge that they exist. How about:
1) We add links to all that we can find at the bottom of https://github.com/Muscula/json-schema-benchmark/blob/master/README.md
2) We try to take the best parts of all (a more realistic set of schemas/objects to validate) and use that as per this issue: https://github.com/Muscula/json-schema-benchmark/issues/11.

**Comment by gilesbowkett** [comment]
sure, that's awesome, although I actually just meant here, in this PR, for this project.

I put a comment on 2. re 1, that looks good already.

**Pull request closed without merging**
